# Generated by Django 5.0.6 on 2024-05-31 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_patient_notes_tooth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
    ]
