# Generated by Django 5.0.6 on 2024-07-21 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_patient_image1_patient_image2_patient_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
